name       : libblockdev
version    : '2.11_1'
release    : 1
source     :
    - https://github.com/storaged-project/libblockdev/archive/2.11-1.tar.gz : fd0d51be0e18149e4234f1a63c36493238c68a4a98d837136cbbcfa116a238d1
license    : LGPL-2.1
component  : programming.library
summary    : A library for manipulating block devices
description: |
    The libblockdev is a C library with GObject introspection support that can be
    used for doing low-level operations with block devices like setting up LVM,
    BTRFS, LUKS or MD RAID. The library uses plugins (LVM, BTRFS,...) and serves as
    a thin wrapper around its plugins' functionality. All the plugins, however, can
    be used as standalone libraries. One of the core principles of libblockdev is
    that it is stateless from the storage configuration's perspective (e.g. it has
    no information about VGs when creating an LV).
builddeps  :
    - pkgconfig(bytesize)
    - pkgconfig(devmapper)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libkmod)
    - pkgconfig(libparted)
    - pkgconfig(nss)
    - volume_key-devel
setup      : |
    %reconfigure --without-dm
build      : |
    %make
install    : |
    %make_install
