name       : libblockdev
version    : '3.0.3'
release    : 16
source     :
    - https://github.com/storaged-project/libblockdev/releases/download/3.0.3-1/libblockdev-3.0.3.tar.gz : 0f2872830293f3e222832903d80de4c38e06a9c3ea18915b3263272a72095ea8
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A library for manipulating block devices
description: |
    The libblockdev is a C library with GObject introspection support that can be used for doing low-level operations with block devices like setting up LVM, BTRFS, LUKS or MD RAID.
builddeps  :
    - pkgconfig(bytesize)
    - pkgconfig(devmapper)
    - pkgconfig(ext2fs)
    - pkgconfig(keyutils)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libkmod)
    - pkgconfig(libnvme)
    - pkgconfig(libparted)
    - pkgconfig(nss)
    - autoconf-archive
    - volume_key-devel
setup      : |
    %configure --without-nvdimm
build      : |
    %make
install    : |
    %make_install

    # Stateless
    rm -v $installdir/etc/libblockdev/3/conf.d/00-default.cfg \
          $installdir/etc/libblockdev/3/conf.d/10-lvm-dbus.cfg
    rmdir -v $installdir/etc/libblockdev/3/conf.d/ \
             $installdir/etc/libblockdev/3/ \
             $installdir/etc/libblockdev/ \
             $installdir/etc/
check      : |
    %make check
