name       : libblockdev
version    : '2.23'
release    : 11
source     :
    - https://github.com/storaged-project/libblockdev/releases/download/2.23-1/libblockdev-2.23.tar.gz : 55ce2ab0f598e34dadb11563d62582c52abaf6daf71c6318f215aab99e788795
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A library for manipulating block devices
description: |
    The libblockdev is a C library with GObject introspection support that can be used for doing low-level operations with block devices like setting up LVM, BTRFS, LUKS or MD RAID.
builddeps  :
    - pkgconfig(bytesize)
    - pkgconfig(devmapper)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libkmod)
    - pkgconfig(libparted)
    - pkgconfig(nss)
    - pkgconfig(yaml-0.1)
    - autoconf-archive
    - volume_key-devel
setup      : |
    %configure --without-dm --without-nvdimm
build      : |
    %make
install    : |
    %make_install
    # Drop python2 binding
    rm -fr $installdir/usr/lib/python2.7/
