name       : libblockdev
version    : '2.14'
release    : 2
source     :
    - https://github.com/storaged-project/libblockdev/releases/download/2.14-1/libblockdev-2.14.tar.gz : 423ef4f0093c0a11cc3afd1a90e50e7e93b807a91899ece42f358ffa7aa02486
license    : LGPL-2.1
component  : programming.library
summary    : A library for manipulating block devices
description: |
    The libblockdev is a C library with GObject introspection support that can be
    used for doing low-level operations with block devices like setting up LVM,
    BTRFS, LUKS or MD RAID. The library uses plugins (LVM, BTRFS,...) and serves as
    a thin wrapper around its plugins' functionality. All the plugins, however, can
    be used as standalone libraries. One of the core principles of libblockdev is
    that it is stateless from the storage configuration's perspective (e.g. it has
    no information about VGs when creating an LV).
builddeps  :
    - pkgconfig(bytesize)
    - pkgconfig(devmapper)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libkmod)
    - pkgconfig(libparted)
    - pkgconfig(nss)
    - volume_key-devel
setup      : |
    %reconfigure --without-dm
build      : |
    %make
install    : |
    %make_install
