name       : libblockdev
version    : 2.16
release    : 4
source     :
    - https://github.com/storaged-project/libblockdev/releases/download/2.16-1/libblockdev-2.16.tar.gz : d841ae446cf6dc545e4f7386e13dfd8c3e07c4b6a962536b7c0fcd20e3a4d9e4
license    : LGPL-2.1
component  : programming.library
summary    : A library for manipulating block devices
description: |
    The libblockdev is a C library with GObject introspection support that can be
    used for doing low-level operations with block devices like setting up LVM,
    BTRFS, LUKS or MD RAID. The library uses plugins (LVM, BTRFS,...) and serves as
    a thin wrapper around its plugins' functionality. All the plugins, however, can
    be used as standalone libraries. One of the core principles of libblockdev is
    that it is stateless from the storage configuration's perspective (e.g. it has
    no information about VGs when creating an LV).
builddeps  :
    - pkgconfig(bytesize)
    - pkgconfig(devmapper)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libkmod)
    - pkgconfig(libparted)
    - pkgconfig(nss)
    - volume_key-devel
setup      : |
    %reconfigure --without-dm
build      : |
    %make
install    : |
    %make_install
