name       : libblockdev
version    : '2.22'
release    : 5
source     :
    - https://github.com/storaged-project/libblockdev/archive/2.22-1.tar.gz : 9ffe1526aec93994978c1b1b93a90e4ed762fed1819e907bae4ed14c859882fe
license    : LGPL-2.1
component  : programming.library
summary    : A library for manipulating block devices
description: |
    The libblockdev is a C library with GObject introspection support that can be
    used for doing low-level operations with block devices like setting up LVM,
    BTRFS, LUKS or MD RAID. The library uses plugins (LVM, BTRFS,...) and serves as
    a thin wrapper around its plugins' functionality. All the plugins, however, can
    be used as standalone libraries. One of the core principles of libblockdev is
    that it is stateless from the storage configuration's perspective (e.g. it has
    no information about VGs when creating an LV).
builddeps  :
    - pkgconfig(bytesize)
    - pkgconfig(devmapper)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libkmod)
    - pkgconfig(libparted)
    - pkgconfig(nss)
    - pkgconfig(yaml-0.1)
    - autoconf-archive
    - volume_key-devel
setup      : |
    %autogen --without-dm --without-nvdimm
build      : |
    %make
install    : |
    %make_install
